### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by XorOwl**
enunciated problem with patching, as blizzard provides version 1.14b but latest is 1.14d. highly miss-able as an important component

### CODE REVIEW

**Comment by theBGuy** [comment]
You don't need to download the patch from an external site, if you open the game directly without using d2bot and log in to bnet it will download the patch.

**Comment by XorOwl** [comment]
Nope. Battle.net updater is borked. It downloads a corrupted package that breaks your install into a crash loop at worst, and just doesn't work at best.

**Comment by ejt1** [comment]
Indeed sometimes patching bugs out but you can download the patch manually from [Blizzards official website](https://eu.battle.net/support/pt/article/13867)

Or direct link for the expansion [here](http://ftp.blizzard.com/pub/diablo2exp/patches/PC/LODPatch_114d.exe)

**Comment by XorOwl** [comment]
You're right! that would be a better direction to send them, though the first link you linked suggests you use battle net, which, doesnt work, however the second link would.
Either way i think something can be put in to make this easier

**Comment by ejt1** [comment]
The second link comes from the first link so there's no issues with either of them.

**Comment by XorOwl** [comment]
im blind
i blame the tiny footnote that the links reside in

**Comment by mf022** [comment]
we posted long time ago 1.13-1.14 patches: https://github.com/blizzhackers/diablo2-tools-utilities/tree/master/Patches

**Pull request closed without merging**
